program: main.py
name: pretrainedsweep
project: WinningKaggle
entity: hugo-debosschere-are-na
method: random 
metric:
  goal: maximize
  name: f1score


parameters:
  
  data.trainpath:
    value: '/mounts/datasets/datasets/2025-ZooCamChallenge/train'
  data.testpath:
    value: '/mounts/datasets/datasets/2025-ZooCamChallenge/test'
  data.batch_size:
    value: 512
  data.num_workers:
    value: 64
  data.valid_ratio:
    value: 0.2
  data.is_batch_weighted :
    value: False #If True, The dataloader are initialized with a RandomWeightedSampler

  
  optim.algo:
    value : AdamW
  optim.params.lr:
      value : 0.001
  optim.params.weight_decay:
      value : 0.001
  optim.params.amsgrad:
    value: True

    
  loss.lossname:
    value: "FocalLoss"
  loss.is_weighted:
    value: False
  loss.gamma:
    value: 2


  
  train.nepochs: 
    value: 128
  train.is_weighted:
    values: False #if True, the selected loss is called with get_weighted_loss, which gives a stronger loss to rarer samples
  train.test_end_train:
    value: True

  
  logging.logdir:
    value: "~/DeepLearning/pytorch_template_code/logs"  # Better to provide the fullpath, especially on the cluster
  logging.save_dir :
    value: /usr/users/sdim/sdim_9/DeepLearning/pytorch_template_code/test


  model.ona100: True
  model.pretrained_path:
    value: "hf_hub:Jookare/plankton_vit_large_patch16_224.mae"
  model.pretrained_in_color:
    value: True 

