data:
  trainpath: '/mounts/datasets/datasets/2025-ZooCamChallenge/train'
  testpath: '/mounts/datasets/datasets/2025-ZooCamChallenge/test'
  batch_size: 256
  num_workers: 8
  valid_ratio: 0.2

optim:
  algo: AdamW
  params:
    lr: 0.01

nepochs: 20
loss: "CrossEntropyLoss"

logging:
  # wandb: 
  #   project: sample_project
  #   entity: sample_entity
  logdir: "./logs"  # Better to provide the fullpath, especially on the cluster
# model:
#   class: Linear
model:
  class: VanillaCNN
  num_layers : 4

test:
  model_name: "./logs/VanillaCNN_2/best_model.pt"
  save_dir: "./test"