#!/bin/bash                                                                                                                                         
 
#SBATCH --job-name=9training                                                                                                                        
#SBATCH --nodes=1                                                                                                                            
#SBATCH --partition=gpu_prod_long                                                                                                                   
#SBATCH --time=24:00:00                                                                                                                              
                                                                                                                      
 
echo "hello world"
while true
do
  sleep 1000
done

