program: main.py
name: newpretrainedsweep
project: WinningKaggle
entity: hugo-debosschere-are-na
method: random 
count : 132
metric:
  goal: maximize
  name: f1score


parameters:
  data.trainpath:
    value: '$TMPDIR/dataset/train'
  data.testpath:
    value: '$TMPDIR/dataset/test'
  data.batch_size:
    value: 128
  data.num_workers:
    value: 4
  data.valid_ratio:
    value: 0.2
  data.is_batch_weighted :
    value: False #If True, The dataloader are initialized with a RandomWeightedSampler

  
  optim.algo:
    value : AdamW
  optim.params.lr:
    value : 0.001
  optim.params.weight_decay:
    value: 0.0
  optim.params.amsgrad:
    value: True

    
  loss.lossname:
    value: "CrossEntropyLoss"
  loss.is_weighted:
    value: False
  loss.gamma:
    value: 2


  
  train.nepochs: 
    value: 128
  train.is_weighted:
    value: False #if True, the selected loss is called with get_weighted_loss, which gives a stronger loss to rarer samples
  train.test_end_train:
    value: True

  
  logging.logdir:
    value: "~/DeepLearning/pytorch_template_code/logs"  # Better to provide the fullpath, especially on the cluster
  logging.save_dir :
    value: /usr/users/sdim/sdim_9/DeepLearning/pytorch_template_code/test

  model.class:
    value: PollenNet
  model.num_layers:
    value: 3
  model.size_linear :
    value: 256
  model.prob_droupout:
    value: 0.0
  model.ona100: 
    value : True
  model.pretrained_path:
    value:  "convnextv2_tiny.fcmae_ft_in22k_in1k"
  model.pretrained_in_color:
    value: True 
  model.old_model_path:
    value: "/raid/home/students/hugodebosschere/DeepLearning/pytorch_template_code/logs/VanillaCNN_68/best_model.pt"




#'vit_small_plus_patch16_dinov3.lvd1689m'
#"convnextv2_tiny.fcmae_ft_in22k_in1k" -> /raid/home/students/hugodebosschere/DeepLearning/pytorch_template_code/logs/VanillaCNN_68
#'vit_base_patch16_dinov3.lvd1689m'
#'efficientnet_b3.ra2_in1k'
#'convnext_tiny.dinov3_lvd1689m' -> not good
#'resnet50.a1_in1k' -> not good 
#'levit_128s.fb_dist_in1k'
#'levit_256.fb_dist_in1k'
#'tiny_vit_11m_224.dist_in22k_ft_in1k' -> not good
#'vit_base_patch16_clip_224.laion2b_ft_in12k_in1k' -> pretty good
#'tinynet_e.in1k' 
#"hf_hub:Jookare/plankton_vit_large_patch16_224.mae"