program: main.py
name: sweepdemo
project: WinningKaggle
entity: hugo-debosschere-are-na
count: 100
method: bayes
metric:
  goal: maximize
  name: f1score
parameters:
  
  data.trainpath:
    value: '/mounts/datasets/datasets/2025-ZooCamChallenge/train'
  data.testpath:
    value: '/mounts/datasets/datasets/2025-ZooCamChallenge/test'
  data.batch_size:
    values: [1024,2048]
  data.num_workers:
    value: 8
  data.valid_ratio:
    value: 0.2
  data.is_batch_weighted :
    value: False #If True, The dataloader are initialized with a RandomWeightedSampler

  
  optim.algo:
    value : AdamW
  optim.params.lr:
      distribution: log_uniform_values
      max: 0.1 
      min : 0.0001
  optim.params.weight_decay:
      distribution: log_uniform_values
      max: 0.5 
      min : 0.0001
  optim.params.amsgrad:
    values: [True, False]

    
  loss.lossname:
    values: ["FocalLoss","CrossEntropyLoss"]
  loss.is_weighted:
    values: [True, False] 
  loss.gamma:
    distribution: uniform
    max: 10
    min: 1


  
  train.nepochs: 
    values: [20, 50, 100, 150, 200]
  train.is_weighted:
    values: [True, False] #if True, the selected loss is called with get_weighted_loss, which gives a stronger loss to rarer samples
  train.test_end_train:
    value: True

  
  logging.logdir:
    value: "~/DeepLearning/pytorch_template_code/logs"  # Better to provide the fullpath, especially on the cluster
  logging.save_dir :
    value: /usr/users/sdim/sdim_9/DeepLearning/pytorch_template_code/test


  
  model.class:
    values: [PollenNet,VanillaCNN]
  model.num_layers:
    values: [3,4,5] 
  model.size_linear :
    values: [256,521,1024]
  model.prob_droupout:
    min: 0.0 
    max : 0.99
  #old_model_path : /raid/home/memconflictsllm/hugodebosschere/deep_learning_2025_2026_debosschere_delaby_huhardeaux/pytorch_template_code/logs/PollenNet_4/best_model.pt #if not None, the parameters are going to be ignored
  